udpate README.jp.md
gtensha/OpenTaiko pull request #16
Opened 2019-10-25 16:35 UTC by tanabe

Hello.

I also enhanced Japanese translations of README.jp.md.

thanks.

2019-10-28 18:58 UTC, gtensha requested changes
Hello, thank you for your continued contributions. I really appreciate it.
I'm thoroughly satisfied with this translation. It really raises the quality of the project.

This time I have two things I'd like you to look at before I merge your changes. Let me know if anything is unclear. Thanks!

2019-10-28 18:58 UTC, gtensha commented on README.jp.md
> +キーの設定は _keybinds.json_ に登録しています。このファイルはテキストエディタで変更しても平気です。設定は選択したプレイヤーのみ有効です。他のプレイヤーには影響しません。
This is good, but the last two sentences may not convey what I wanted to say. Sorry for the vagueness.
「設定は選択したナンバーのプレイヤーのみ有効です」でどうでしょうか。
For example, when you set keybinds for player 2, the keybindings will always be the same no matter which player name enters as player 2 in the game session.

2019-10-28 18:58 UTC, gtensha commented on README.jp.md
> +遊ぶ時にプレイヤー 1 の叩くキーはデフォールト [D F J K] に設定されています。D は左カツで、F は左ドンと言う感じになります。プレイヤー 2 の場合は [End PageDown Numpad8 Numpad9] に設定されています。
As we had this change before;
左カツ → 左カッ？

2019-10-29 15:26 UTC, tanabe commented on README.jp.md
> +遊ぶ時にプレイヤー 1 の叩くキーはデフォールト [D F J K] に設定されています。D は左カツで、F は左ドンと言う感じになります。プレイヤー 2 の場合は [End PageDown Numpad8 Numpad9] に設定されています。
Yes, that's right!

2019-10-29 21:46 UTC, gtensha approved these changes
Excellent. Thank you very much!

2019-10-29 21:48 UTC, merged